
pipeline {
agent any
    stages() {
        stage('git clone') {
            steps() {
                git 'https://github.com/sungahChooo/book2.git'
            }    
        }
    
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
    
        stage('execute sh') {
            steps {
                sh "chmod 774 ./book.sh"
                sh "./book.sh"
            }
        }        
    }
}
