pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
		sh 'javac -encoding UTF-8 -d classes Practice/src/**/*.java'
                
            }
        }
        stage('Test') {
            steps {
                def classpth= "C:/Users/LG_PC/eclipse/java-2024-03/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar" bat 'java -cp classes C:/Users/LG_PC/eclipse/java-2024-03/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar
org.junit.platform.console.ConsoleLauncher --scan-classpath > test_result.txt'
            }
        }
    }
post{
	always{
archiveArtifacts 'test_results.txt'
}
failure{
	echo 'Build or test failed'
}
success{
echo 'Build and test succeeded'
}
}
}
